/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tq.test;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.stub.StreamObserver;
import java.io.IOException;
import java.util.logging.Logger;
import com.tq.test.helloworld.HelloRequest;
import com.tq.test.helloworld.HelloReply;
import com.tq.test.helloworld.GreeterGrpc;

public class App {

    private static final Logger logger = Logger.getLogger(App.class.getName());
    private Server server;
    
    public static void main(String[] args) {
        try {
            final App app = new App();
            app.start();
            app.blockUntilShutdown();
        } catch (Exception e) {
            logger.info(e.getMessage());
        }
    }

    private void start() throws IOException {
        int port = 50051;
        server = ServerBuilder.forPort(port)
            .addService(new GreeterImpl())
            .build()
            .start();
        logger.info("started");
        Runtime.getRuntime().addShutdownHook(new Thread() {
                @Override
                public void run() {
                    App.this.stop();
                    System.err.println("shutdown");
                }
            });
    }

    private void stop() {
        if (server != null) {
            server.shutdown();
        }
    }

    private void blockUntilShutdown() throws InterruptedException {
        if (server != null) {
            server.awaitTermination();
        }
    }

    static class GreeterImpl extends GreeterGrpc.GreeterImplBase {
        @Override
        public void sayHello(HelloRequest req, StreamObserver<HelloReply> observer) {
            HelloReply reply = HelloReply.newBuilder()
                .setMessage("Hello " + req.getName())
                .build();

            observer.onNext(reply);
            observer.onCompleted();
        }
    }
}
