package build;

/**
 * GENERATED BY buildinfo-maven-plugin
 */

public final class BuildInfo {
    public static final String HEAD = "(HEAD)";
    public static final String ORIG_HEAD = "(ORIG_HEAD)";
    public static final String BRANCH = "(BRANCH)";
    public static final boolean HAVE_UNCOMMITTED_CHANGES = (HAVE_UNCOMMITTED_CHANGES);
}
