/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tq.test;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.StatusRuntimeException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Logger;
import com.tq.test.helloworld.HelloRequest;
import com.tq.test.helloworld.HelloReply;
import com.tq.test.helloworld.GreeterGrpc;

public class App {

    private static final Logger logger = Logger.getLogger(App.class.getName());
    private final ManagedChannel channel;
    private final GreeterGrpc.GreeterBlockingStub blockingStub;

    public App(String host, int port) {
        this(ManagedChannelBuilder.forAddress(host, port)
             .usePlaintext()
             .build());
    }

    private App(ManagedChannel channel) {
        this.channel = channel;
        blockingStub = GreeterGrpc.newBlockingStub(channel);
    }

    public void shutdown() throws InterruptedException {
        channel.shutdown().awaitTermination(5, TimeUnit.SECONDS);
    }

    public void greet(String name) {
        HelloRequest request = HelloRequest.newBuilder()
            .setName(name)
            .build();

        try {
            HelloReply response = blockingStub.sayHello(request);
            logger.info(response.getMessage());
        } catch (Exception e) {
            logger.info(e.getMessage());
        }
    }
    
    public static void main(String[] args) {
        final App app = new App("localhost", 50051);
        try {
            app.greet("world");
            app.shutdown();
        } catch (Exception e) {
            logger.info(e.getMessage());
        }
    }  
}
