/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Redis;

import io.lettuce.core.*;
import io.lettuce.core.api.*;
import io.lettuce.core.api.sync.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        String host = "192.168.1.104";
        int port = 6379;

        RedisClient redisClient = RedisClient.create("redis://@192.168.1.104:6379/0");
        StatefulRedisConnection<String,String> connection = redisClient.connect();
        RedisCommands<String,String> syncCommands = connection.sync();
        syncCommands.set("key", "Hello, Redis!");
        connection.close();
        redisClient.shutdown();
        
        System.out.println(new App().getGreeting());
    }
}
