// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.tq.microservice.common;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_InstanceId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_InstanceId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ProxyHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_ProxyHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ProxyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_ProxyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ProxyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_ProxyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\006common\032\031google/protobuf/" +
      "any.proto\"G\n\nInstanceId\022\n\n\002ip\030\001 \001(\005\022\014\n\004p" +
      "ort\030\002 \001(\005\022\022\n\nstart_time\030\003 \001(\005\022\013\n\003pid\030\004 \001" +
      "(\005\"U\n\013ProxyHeader\022\"\n\006source\030\001 \001(\0132\022.comm" +
      "on.InstanceId\022\"\n\006target\030\002 \001(\0132\022.common.I" +
      "nstanceId\"\211\001\n\014ProxyRequest\022#\n\006header\030\001 \001" +
      "(\0132\023.common.ProxyHeader\022\024\n\014service_name\030" +
      "\002 \001(\t\022\027\n\017service_version\030\003 \001(\t\022%\n\007payloa" +
      "d\030\004 \001(\0132\024.google.protobuf.Any\"\250\001\n\rProxyR" +
      "esponse\022#\n\006header\030\001 \001(\0132\023.common.ProxyHe" +
      "ader\022\024\n\014service_name\030\002 \001(\t\022\027\n\017service_ve" +
      "rsion\030\003 \001(\t\022\034\n\005error\030\004 \001(\0162\r.common.Erro" +
      "r\022%\n\007payload\030\005 \001(\0132\024.google.protobuf.Any" +
      "*B\n\005Error\022\014\n\010NO_ERROR\020\000\022\023\n\017INVALID_REQUE" +
      "ST\020\001\022\026\n\022INSTANCE_NOT_FOUND\020\002B+\n\032com.tq.m" +
      "icroservice.commonB\013CommonProtoP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_common_InstanceId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_InstanceId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_InstanceId_descriptor,
        new java.lang.String[] { "Ip", "Port", "StartTime", "Pid", });
    internal_static_common_ProxyHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_ProxyHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_ProxyHeader_descriptor,
        new java.lang.String[] { "Source", "Target", });
    internal_static_common_ProxyRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_common_ProxyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_ProxyRequest_descriptor,
        new java.lang.String[] { "Header", "ServiceName", "ServiceVersion", "Payload", });
    internal_static_common_ProxyResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_common_ProxyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_ProxyResponse_descriptor,
        new java.lang.String[] { "Header", "ServiceName", "ServiceVersion", "Error", "Payload", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
