// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.tq.microservice.common;

/**
 * <pre>
 * common error code
 * </pre>
 *
 * Protobuf enum {@code common.Error}
 */
public enum Error
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NO_ERROR = 0;</code>
   */
  NO_ERROR(0),
  /**
   * <code>INVALID_REQUEST = 1;</code>
   */
  INVALID_REQUEST(1),
  /**
   * <code>INSTANCE_NOT_FOUND = 2;</code>
   */
  INSTANCE_NOT_FOUND(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NO_ERROR = 0;</code>
   */
  public static final int NO_ERROR_VALUE = 0;
  /**
   * <code>INVALID_REQUEST = 1;</code>
   */
  public static final int INVALID_REQUEST_VALUE = 1;
  /**
   * <code>INSTANCE_NOT_FOUND = 2;</code>
   */
  public static final int INSTANCE_NOT_FOUND_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Error valueOf(int value) {
    return forNumber(value);
  }

  public static Error forNumber(int value) {
    switch (value) {
      case 0: return NO_ERROR;
      case 1: return INVALID_REQUEST;
      case 2: return INSTANCE_NOT_FOUND;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Error>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Error> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Error>() {
          public Error findValueByNumber(int number) {
            return Error.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.tq.microservice.common.CommonProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final Error[] VALUES = values();

  public static Error valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Error(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:common.Error)
}

