// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.tq.microservice.common;

public interface InstanceIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.InstanceId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ip = 1;</code>
   */
  int getIp();

  /**
   * <pre>
   * 0 for ignore this field
   * </pre>
   *
   * <code>int32 port = 2;</code>
   */
  int getPort();

  /**
   * <pre>
   * 0 for ignore this field
   * </pre>
   *
   * <code>int32 start_time = 3;</code>
   */
  int getStartTime();

  /**
   * <pre>
   * 0 for ignore this field
   * </pre>
   *
   * <code>int32 pid = 4;</code>
   */
  int getPid();
}
