// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.tq.microservice.common;

public interface ProxyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.ProxyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.ProxyHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.common.ProxyHeader header = 1;</code>
   */
  com.tq.microservice.common.ProxyHeader getHeader();
  /**
   * <code>.common.ProxyHeader header = 1;</code>
   */
  com.tq.microservice.common.ProxyHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>string service_name = 2;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string service_version = 3;</code>
   */
  java.lang.String getServiceVersion();
  /**
   * <code>string service_version = 3;</code>
   */
  com.google.protobuf.ByteString
      getServiceVersionBytes();

  /**
   * <code>.google.protobuf.Any payload = 4;</code>
   */
  boolean hasPayload();
  /**
   * <code>.google.protobuf.Any payload = 4;</code>
   */
  com.google.protobuf.Any getPayload();
  /**
   * <code>.google.protobuf.Any payload = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getPayloadOrBuilder();
}
