// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.tq.microservice.common;

/**
 * <pre>
 * common header
 * </pre>
 *
 * Protobuf type {@code common.ProxyHeader}
 */
public  final class ProxyHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:common.ProxyHeader)
    ProxyHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProxyHeader.newBuilder() to construct.
  private ProxyHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProxyHeader() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProxyHeader(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.tq.microservice.common.InstanceId.Builder subBuilder = null;
            if (source_ != null) {
              subBuilder = source_.toBuilder();
            }
            source_ = input.readMessage(com.tq.microservice.common.InstanceId.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(source_);
              source_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.tq.microservice.common.InstanceId.Builder subBuilder = null;
            if (target_ != null) {
              subBuilder = target_.toBuilder();
            }
            target_ = input.readMessage(com.tq.microservice.common.InstanceId.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(target_);
              target_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tq.microservice.common.CommonProto.internal_static_common_ProxyHeader_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tq.microservice.common.CommonProto.internal_static_common_ProxyHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tq.microservice.common.ProxyHeader.class, com.tq.microservice.common.ProxyHeader.Builder.class);
  }

  public static final int SOURCE_FIELD_NUMBER = 1;
  private com.tq.microservice.common.InstanceId source_;
  /**
   * <code>.common.InstanceId source = 1;</code>
   */
  public boolean hasSource() {
    return source_ != null;
  }
  /**
   * <code>.common.InstanceId source = 1;</code>
   */
  public com.tq.microservice.common.InstanceId getSource() {
    return source_ == null ? com.tq.microservice.common.InstanceId.getDefaultInstance() : source_;
  }
  /**
   * <code>.common.InstanceId source = 1;</code>
   */
  public com.tq.microservice.common.InstanceIdOrBuilder getSourceOrBuilder() {
    return getSource();
  }

  public static final int TARGET_FIELD_NUMBER = 2;
  private com.tq.microservice.common.InstanceId target_;
  /**
   * <code>.common.InstanceId target = 2;</code>
   */
  public boolean hasTarget() {
    return target_ != null;
  }
  /**
   * <code>.common.InstanceId target = 2;</code>
   */
  public com.tq.microservice.common.InstanceId getTarget() {
    return target_ == null ? com.tq.microservice.common.InstanceId.getDefaultInstance() : target_;
  }
  /**
   * <code>.common.InstanceId target = 2;</code>
   */
  public com.tq.microservice.common.InstanceIdOrBuilder getTargetOrBuilder() {
    return getTarget();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (source_ != null) {
      output.writeMessage(1, getSource());
    }
    if (target_ != null) {
      output.writeMessage(2, getTarget());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (source_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSource());
    }
    if (target_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTarget());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tq.microservice.common.ProxyHeader)) {
      return super.equals(obj);
    }
    com.tq.microservice.common.ProxyHeader other = (com.tq.microservice.common.ProxyHeader) obj;

    boolean result = true;
    result = result && (hasSource() == other.hasSource());
    if (hasSource()) {
      result = result && getSource()
          .equals(other.getSource());
    }
    result = result && (hasTarget() == other.hasTarget());
    if (hasTarget()) {
      result = result && getTarget()
          .equals(other.getTarget());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSource()) {
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
    }
    if (hasTarget()) {
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTarget().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tq.microservice.common.ProxyHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tq.microservice.common.ProxyHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tq.microservice.common.ProxyHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tq.microservice.common.ProxyHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tq.microservice.common.ProxyHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tq.microservice.common.ProxyHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tq.microservice.common.ProxyHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tq.microservice.common.ProxyHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tq.microservice.common.ProxyHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tq.microservice.common.ProxyHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tq.microservice.common.ProxyHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tq.microservice.common.ProxyHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tq.microservice.common.ProxyHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * common header
   * </pre>
   *
   * Protobuf type {@code common.ProxyHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.ProxyHeader)
      com.tq.microservice.common.ProxyHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tq.microservice.common.CommonProto.internal_static_common_ProxyHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tq.microservice.common.CommonProto.internal_static_common_ProxyHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tq.microservice.common.ProxyHeader.class, com.tq.microservice.common.ProxyHeader.Builder.class);
    }

    // Construct using com.tq.microservice.common.ProxyHeader.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (sourceBuilder_ == null) {
        source_ = null;
      } else {
        source_ = null;
        sourceBuilder_ = null;
      }
      if (targetBuilder_ == null) {
        target_ = null;
      } else {
        target_ = null;
        targetBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tq.microservice.common.CommonProto.internal_static_common_ProxyHeader_descriptor;
    }

    @java.lang.Override
    public com.tq.microservice.common.ProxyHeader getDefaultInstanceForType() {
      return com.tq.microservice.common.ProxyHeader.getDefaultInstance();
    }

    @java.lang.Override
    public com.tq.microservice.common.ProxyHeader build() {
      com.tq.microservice.common.ProxyHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tq.microservice.common.ProxyHeader buildPartial() {
      com.tq.microservice.common.ProxyHeader result = new com.tq.microservice.common.ProxyHeader(this);
      if (sourceBuilder_ == null) {
        result.source_ = source_;
      } else {
        result.source_ = sourceBuilder_.build();
      }
      if (targetBuilder_ == null) {
        result.target_ = target_;
      } else {
        result.target_ = targetBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tq.microservice.common.ProxyHeader) {
        return mergeFrom((com.tq.microservice.common.ProxyHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tq.microservice.common.ProxyHeader other) {
      if (other == com.tq.microservice.common.ProxyHeader.getDefaultInstance()) return this;
      if (other.hasSource()) {
        mergeSource(other.getSource());
      }
      if (other.hasTarget()) {
        mergeTarget(other.getTarget());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tq.microservice.common.ProxyHeader parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tq.microservice.common.ProxyHeader) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.tq.microservice.common.InstanceId source_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tq.microservice.common.InstanceId, com.tq.microservice.common.InstanceId.Builder, com.tq.microservice.common.InstanceIdOrBuilder> sourceBuilder_;
    /**
     * <code>.common.InstanceId source = 1;</code>
     */
    public boolean hasSource() {
      return sourceBuilder_ != null || source_ != null;
    }
    /**
     * <code>.common.InstanceId source = 1;</code>
     */
    public com.tq.microservice.common.InstanceId getSource() {
      if (sourceBuilder_ == null) {
        return source_ == null ? com.tq.microservice.common.InstanceId.getDefaultInstance() : source_;
      } else {
        return sourceBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.InstanceId source = 1;</code>
     */
    public Builder setSource(com.tq.microservice.common.InstanceId value) {
      if (sourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        source_ = value;
        onChanged();
      } else {
        sourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.common.InstanceId source = 1;</code>
     */
    public Builder setSource(
        com.tq.microservice.common.InstanceId.Builder builderForValue) {
      if (sourceBuilder_ == null) {
        source_ = builderForValue.build();
        onChanged();
      } else {
        sourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.common.InstanceId source = 1;</code>
     */
    public Builder mergeSource(com.tq.microservice.common.InstanceId value) {
      if (sourceBuilder_ == null) {
        if (source_ != null) {
          source_ =
            com.tq.microservice.common.InstanceId.newBuilder(source_).mergeFrom(value).buildPartial();
        } else {
          source_ = value;
        }
        onChanged();
      } else {
        sourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.common.InstanceId source = 1;</code>
     */
    public Builder clearSource() {
      if (sourceBuilder_ == null) {
        source_ = null;
        onChanged();
      } else {
        source_ = null;
        sourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.common.InstanceId source = 1;</code>
     */
    public com.tq.microservice.common.InstanceId.Builder getSourceBuilder() {
      
      onChanged();
      return getSourceFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.InstanceId source = 1;</code>
     */
    public com.tq.microservice.common.InstanceIdOrBuilder getSourceOrBuilder() {
      if (sourceBuilder_ != null) {
        return sourceBuilder_.getMessageOrBuilder();
      } else {
        return source_ == null ?
            com.tq.microservice.common.InstanceId.getDefaultInstance() : source_;
      }
    }
    /**
     * <code>.common.InstanceId source = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tq.microservice.common.InstanceId, com.tq.microservice.common.InstanceId.Builder, com.tq.microservice.common.InstanceIdOrBuilder> 
        getSourceFieldBuilder() {
      if (sourceBuilder_ == null) {
        sourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tq.microservice.common.InstanceId, com.tq.microservice.common.InstanceId.Builder, com.tq.microservice.common.InstanceIdOrBuilder>(
                getSource(),
                getParentForChildren(),
                isClean());
        source_ = null;
      }
      return sourceBuilder_;
    }

    private com.tq.microservice.common.InstanceId target_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tq.microservice.common.InstanceId, com.tq.microservice.common.InstanceId.Builder, com.tq.microservice.common.InstanceIdOrBuilder> targetBuilder_;
    /**
     * <code>.common.InstanceId target = 2;</code>
     */
    public boolean hasTarget() {
      return targetBuilder_ != null || target_ != null;
    }
    /**
     * <code>.common.InstanceId target = 2;</code>
     */
    public com.tq.microservice.common.InstanceId getTarget() {
      if (targetBuilder_ == null) {
        return target_ == null ? com.tq.microservice.common.InstanceId.getDefaultInstance() : target_;
      } else {
        return targetBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.InstanceId target = 2;</code>
     */
    public Builder setTarget(com.tq.microservice.common.InstanceId value) {
      if (targetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        target_ = value;
        onChanged();
      } else {
        targetBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.common.InstanceId target = 2;</code>
     */
    public Builder setTarget(
        com.tq.microservice.common.InstanceId.Builder builderForValue) {
      if (targetBuilder_ == null) {
        target_ = builderForValue.build();
        onChanged();
      } else {
        targetBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.common.InstanceId target = 2;</code>
     */
    public Builder mergeTarget(com.tq.microservice.common.InstanceId value) {
      if (targetBuilder_ == null) {
        if (target_ != null) {
          target_ =
            com.tq.microservice.common.InstanceId.newBuilder(target_).mergeFrom(value).buildPartial();
        } else {
          target_ = value;
        }
        onChanged();
      } else {
        targetBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.common.InstanceId target = 2;</code>
     */
    public Builder clearTarget() {
      if (targetBuilder_ == null) {
        target_ = null;
        onChanged();
      } else {
        target_ = null;
        targetBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.common.InstanceId target = 2;</code>
     */
    public com.tq.microservice.common.InstanceId.Builder getTargetBuilder() {
      
      onChanged();
      return getTargetFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.InstanceId target = 2;</code>
     */
    public com.tq.microservice.common.InstanceIdOrBuilder getTargetOrBuilder() {
      if (targetBuilder_ != null) {
        return targetBuilder_.getMessageOrBuilder();
      } else {
        return target_ == null ?
            com.tq.microservice.common.InstanceId.getDefaultInstance() : target_;
      }
    }
    /**
     * <code>.common.InstanceId target = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tq.microservice.common.InstanceId, com.tq.microservice.common.InstanceId.Builder, com.tq.microservice.common.InstanceIdOrBuilder> 
        getTargetFieldBuilder() {
      if (targetBuilder_ == null) {
        targetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tq.microservice.common.InstanceId, com.tq.microservice.common.InstanceId.Builder, com.tq.microservice.common.InstanceIdOrBuilder>(
                getTarget(),
                getParentForChildren(),
                isClean());
        target_ = null;
      }
      return targetBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:common.ProxyHeader)
  }

  // @@protoc_insertion_point(class_scope:common.ProxyHeader)
  private static final com.tq.microservice.common.ProxyHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tq.microservice.common.ProxyHeader();
  }

  public static com.tq.microservice.common.ProxyHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProxyHeader>
      PARSER = new com.google.protobuf.AbstractParser<ProxyHeader>() {
    @java.lang.Override
    public ProxyHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProxyHeader(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProxyHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProxyHeader> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tq.microservice.common.ProxyHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

