// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.tq.microservice.common;

public interface ProxyHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.ProxyHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.InstanceId source = 1;</code>
   */
  boolean hasSource();
  /**
   * <code>.common.InstanceId source = 1;</code>
   */
  com.tq.microservice.common.InstanceId getSource();
  /**
   * <code>.common.InstanceId source = 1;</code>
   */
  com.tq.microservice.common.InstanceIdOrBuilder getSourceOrBuilder();

  /**
   * <code>.common.InstanceId target = 2;</code>
   */
  boolean hasTarget();
  /**
   * <code>.common.InstanceId target = 2;</code>
   */
  com.tq.microservice.common.InstanceId getTarget();
  /**
   * <code>.common.InstanceId target = 2;</code>
   */
  com.tq.microservice.common.InstanceIdOrBuilder getTargetOrBuilder();
}
