/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tq.microservice.common;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
