package main

import (
	"time"
)

const (
	ID_FILE_IDENTITY_CARD = iota
	ID_FILE_MACAO_PERMANENT_IDENTITY_CARD
	ID_FILE_HONGKONG_PERMANENT_IDENTITY_CARD
	ID_FILE_TRAVEL_PERMIT_HONGKONG_AND_MACAU
	ID_FILE_TRAVEL_PERMIT_TAIWAN
	ID_FILE_PASSPORT
	ID_FILE_PERMANENT_RESIDENCE_OF_FOREIGNERS
	ID_FILE_PERMANENT_RESIDENCE_OF_HONGKONG_MACAU_TAIWAN
	ID_FILE_OTHER
)

type IDFile struct {
	Type            int
	Number          string
	ExpiryDate      time.Time
	RegisterAddress string
}

const (
	EDUCATION_UNKNOWN = iota
	EDUCATION_JUNIOR_MIDDLE_SCHOOL
	EDUCATION_SENIOR_MIDDLE_SCHOOL
	EDUCATION_TECHNICAL_SCHOOL
	EDUCATION_JUNIOR_COLLEGE
	EDUCATION_BACHELOR
	EDUCATION_MASTER
	EDUCATION_DOCTOR
)

const (
	CAREER_PROFESSIONALS = iota
	CAREER_GOVERNMENT_CADRE
	CAREER_FARMER
	CAREER_SELFEMPLOYED
	CAREER_UNEMPLOYED
	CAREER_SOLDIER
	CAREER_STUDENT
	CAREER_WORKER
	CAREER_SECURITY_ASSOCIATED
	CAREER_RETIRED
	CAREER_OTHER
)

const (
	ACCOUNT_OPEN_TYPE_ATTEND = iota
	ACCOUNT_OPEN_TYPE_WITNESS
	ACCOUNT_OPEN_TYPE_ONLINE
)
