// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instanceregisterservice.proto

package com.tq.microservice.instanceregisterservice;

public final class InstanceRegisterServiceProto {
  private InstanceRegisterServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instanceregisterservice_RegisterInstanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_instanceregisterservice_RegisterInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instanceregisterservice_RegisterInstanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_instanceregisterservice_RegisterInstanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instanceregisterservice_UnregisterInstanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_instanceregisterservice_UnregisterInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instanceregisterservice_UnregisterInstanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_instanceregisterservice_UnregisterInstanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instanceregisterservice_QueryServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_instanceregisterservice_QueryServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instanceregisterservice_QueryServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_instanceregisterservice_QueryServiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instanceregisterservice_QueryServiceCatalogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_instanceregisterservice_QueryServiceCatalogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instanceregisterservice_QueryServiceCatalogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_instanceregisterservice_QueryServiceCatalogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035instanceregisterservice.proto\022\027instanc" +
      "eregisterservice\032\014common.proto\"\245\001\n\027Regis" +
      "terInstanceRequest\0223\n\004type\030\001 \001(\0162%.insta" +
      "nceregisterservice.InstanceType\022&\n\ninsta" +
      "nceId\030\002 \001(\0132\022.common.InstanceId\022\024\n\014servi" +
      "ce_name\030\003 \001(\t\022\027\n\017service_version\030\004 \001(\t\"\032" +
      "\n\030RegisterInstanceResponse\"\247\001\n\031Unregiste" +
      "rInstanceRequest\0223\n\004type\030\001 \001(\0162%.instanc" +
      "eregisterservice.InstanceType\022&\n\ninstanc" +
      "eId\030\002 \001(\0132\022.common.InstanceId\022\024\n\014service" +
      "_name\030\003 \001(\t\022\027\n\017service_version\030\004 \001(\t\"\034\n\032" +
      "UnregisterInstanceResponse\"D\n\023QueryServi" +
      "ceRequest\022\024\n\014service_name\030\001 \001(\t\022\027\n\017servi" +
      "ce_version\030\002 \001(\t\"l\n\024QueryServiceResponse" +
      "\022\024\n\014service_name\030\001 \001(\t\022\027\n\017service_versio" +
      "n\030\002 \001(\t\022%\n\tinstances\030\003 \003(\0132\022.common.Inst" +
      "anceId\"\034\n\032QueryServiceCatalogRequest\"4\n\033" +
      "QueryServiceCatalogResponse\022\025\n\rservice_n" +
      "ames\030\001 \003(\t*\'\n\014InstanceType\022\013\n\007SERVICE\020\000\022" +
      "\n\n\006CLIENT\020\0012\211\004\n\027InstanceRegisterService\022" +
      "y\n\020RegisterInstance\0220.instanceregisterse" +
      "rvice.RegisterInstanceRequest\0321.instance" +
      "registerservice.RegisterInstanceResponse" +
      "\"\000\022\177\n\022UnregisterInstance\0222.instanceregis" +
      "terservice.UnregisterInstanceRequest\0323.i" +
      "nstanceregisterservice.UnregisterInstanc" +
      "eResponse\"\000\022m\n\014QueryService\022,.instancere" +
      "gisterservice.QueryServiceRequest\032-.inst" +
      "anceregisterservice.QueryServiceResponse" +
      "\"\000\022\202\001\n\023QueryServiceCatalog\0223.instancereg" +
      "isterservice.QueryServiceCatalogRequest\032" +
      "4.instanceregisterservice.QueryServiceCa" +
      "talogResponse\"\000BM\n+com.tq.microservice.i" +
      "nstanceregisterserviceB\034InstanceRegister" +
      "ServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tq.microservice.common.CommonProto.getDescriptor(),
        }, assigner);
    internal_static_instanceregisterservice_RegisterInstanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_instanceregisterservice_RegisterInstanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_instanceregisterservice_RegisterInstanceRequest_descriptor,
        new java.lang.String[] { "Type", "InstanceId", "ServiceName", "ServiceVersion", });
    internal_static_instanceregisterservice_RegisterInstanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_instanceregisterservice_RegisterInstanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_instanceregisterservice_RegisterInstanceResponse_descriptor,
        new java.lang.String[] { });
    internal_static_instanceregisterservice_UnregisterInstanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_instanceregisterservice_UnregisterInstanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_instanceregisterservice_UnregisterInstanceRequest_descriptor,
        new java.lang.String[] { "Type", "InstanceId", "ServiceName", "ServiceVersion", });
    internal_static_instanceregisterservice_UnregisterInstanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_instanceregisterservice_UnregisterInstanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_instanceregisterservice_UnregisterInstanceResponse_descriptor,
        new java.lang.String[] { });
    internal_static_instanceregisterservice_QueryServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_instanceregisterservice_QueryServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_instanceregisterservice_QueryServiceRequest_descriptor,
        new java.lang.String[] { "ServiceName", "ServiceVersion", });
    internal_static_instanceregisterservice_QueryServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_instanceregisterservice_QueryServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_instanceregisterservice_QueryServiceResponse_descriptor,
        new java.lang.String[] { "ServiceName", "ServiceVersion", "Instances", });
    internal_static_instanceregisterservice_QueryServiceCatalogRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_instanceregisterservice_QueryServiceCatalogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_instanceregisterservice_QueryServiceCatalogRequest_descriptor,
        new java.lang.String[] { });
    internal_static_instanceregisterservice_QueryServiceCatalogResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_instanceregisterservice_QueryServiceCatalogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_instanceregisterservice_QueryServiceCatalogResponse_descriptor,
        new java.lang.String[] { "ServiceNames", });
    com.tq.microservice.common.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
