// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instanceregisterservice.proto

package com.tq.microservice.instanceregisterservice;

/**
 * Protobuf enum {@code instanceregisterservice.InstanceType}
 */
public enum InstanceType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SERVICE = 0;</code>
   */
  SERVICE(0),
  /**
   * <code>CLIENT = 1;</code>
   */
  CLIENT(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SERVICE = 0;</code>
   */
  public static final int SERVICE_VALUE = 0;
  /**
   * <code>CLIENT = 1;</code>
   */
  public static final int CLIENT_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static InstanceType valueOf(int value) {
    return forNumber(value);
  }

  public static InstanceType forNumber(int value) {
    switch (value) {
      case 0: return SERVICE;
      case 1: return CLIENT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<InstanceType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      InstanceType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<InstanceType>() {
          public InstanceType findValueByNumber(int number) {
            return InstanceType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.tq.microservice.instanceregisterservice.InstanceRegisterServiceProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final InstanceType[] VALUES = values();

  public static InstanceType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private InstanceType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:instanceregisterservice.InstanceType)
}

