// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instanceregisterservice.proto

package com.tq.microservice.instanceregisterservice;

public interface QueryServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instanceregisterservice.QueryServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_name = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string service_version = 2;</code>
   */
  java.lang.String getServiceVersion();
  /**
   * <code>string service_version = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceVersionBytes();
}
