// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instanceregisterservice.proto

package com.tq.microservice.instanceregisterservice;

public interface QueryServiceCatalogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instanceregisterservice.QueryServiceCatalogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string service_names = 1;</code>
   */
  java.util.List<java.lang.String>
      getServiceNamesList();
  /**
   * <code>repeated string service_names = 1;</code>
   */
  int getServiceNamesCount();
  /**
   * <code>repeated string service_names = 1;</code>
   */
  java.lang.String getServiceNames(int index);
  /**
   * <code>repeated string service_names = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNamesBytes(int index);
}
