// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instanceregisterservice.proto

package com.tq.microservice.instanceregisterservice;

public interface QueryServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instanceregisterservice.QueryServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_name = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string service_version = 2;</code>
   */
  java.lang.String getServiceVersion();
  /**
   * <code>string service_version = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceVersionBytes();

  /**
   * <code>repeated .common.InstanceId instances = 3;</code>
   */
  java.util.List<com.tq.microservice.common.InstanceId> 
      getInstancesList();
  /**
   * <code>repeated .common.InstanceId instances = 3;</code>
   */
  com.tq.microservice.common.InstanceId getInstances(int index);
  /**
   * <code>repeated .common.InstanceId instances = 3;</code>
   */
  int getInstancesCount();
  /**
   * <code>repeated .common.InstanceId instances = 3;</code>
   */
  java.util.List<? extends com.tq.microservice.common.InstanceIdOrBuilder> 
      getInstancesOrBuilderList();
  /**
   * <code>repeated .common.InstanceId instances = 3;</code>
   */
  com.tq.microservice.common.InstanceIdOrBuilder getInstancesOrBuilder(
      int index);
}
