// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instanceregisterservice.proto

package com.tq.microservice.instanceregisterservice;

/**
 * Protobuf type {@code instanceregisterservice.RegisterInstanceRequest}
 */
public  final class RegisterInstanceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:instanceregisterservice.RegisterInstanceRequest)
    RegisterInstanceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegisterInstanceRequest.newBuilder() to construct.
  private RegisterInstanceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterInstanceRequest() {
    type_ = 0;
    serviceName_ = "";
    serviceVersion_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RegisterInstanceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            com.tq.microservice.common.InstanceId.Builder subBuilder = null;
            if (instanceId_ != null) {
              subBuilder = instanceId_.toBuilder();
            }
            instanceId_ = input.readMessage(com.tq.microservice.common.InstanceId.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(instanceId_);
              instanceId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceVersion_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tq.microservice.instanceregisterservice.InstanceRegisterServiceProto.internal_static_instanceregisterservice_RegisterInstanceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tq.microservice.instanceregisterservice.InstanceRegisterServiceProto.internal_static_instanceregisterservice_RegisterInstanceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tq.microservice.instanceregisterservice.RegisterInstanceRequest.class, com.tq.microservice.instanceregisterservice.RegisterInstanceRequest.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.instanceregisterservice.InstanceType type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.instanceregisterservice.InstanceType type = 1;</code>
   */
  public com.tq.microservice.instanceregisterservice.InstanceType getType() {
    @SuppressWarnings("deprecation")
    com.tq.microservice.instanceregisterservice.InstanceType result = com.tq.microservice.instanceregisterservice.InstanceType.valueOf(type_);
    return result == null ? com.tq.microservice.instanceregisterservice.InstanceType.UNRECOGNIZED : result;
  }

  public static final int INSTANCEID_FIELD_NUMBER = 2;
  private com.tq.microservice.common.InstanceId instanceId_;
  /**
   * <code>.common.InstanceId instanceId = 2;</code>
   */
  public boolean hasInstanceId() {
    return instanceId_ != null;
  }
  /**
   * <code>.common.InstanceId instanceId = 2;</code>
   */
  public com.tq.microservice.common.InstanceId getInstanceId() {
    return instanceId_ == null ? com.tq.microservice.common.InstanceId.getDefaultInstance() : instanceId_;
  }
  /**
   * <code>.common.InstanceId instanceId = 2;</code>
   */
  public com.tq.microservice.common.InstanceIdOrBuilder getInstanceIdOrBuilder() {
    return getInstanceId();
  }

  public static final int SERVICE_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object serviceName_;
  /**
   * <code>string service_name = 3;</code>
   */
  public java.lang.String getServiceName() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /**
   * <code>string service_name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICE_VERSION_FIELD_NUMBER = 4;
  private volatile java.lang.Object serviceVersion_;
  /**
   * <code>string service_version = 4;</code>
   */
  public java.lang.String getServiceVersion() {
    java.lang.Object ref = serviceVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string service_version = 4;</code>
   */
  public com.google.protobuf.ByteString
      getServiceVersionBytes() {
    java.lang.Object ref = serviceVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.tq.microservice.instanceregisterservice.InstanceType.SERVICE.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (instanceId_ != null) {
      output.writeMessage(2, getInstanceId());
    }
    if (!getServiceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serviceName_);
    }
    if (!getServiceVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serviceVersion_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.tq.microservice.instanceregisterservice.InstanceType.SERVICE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (instanceId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInstanceId());
    }
    if (!getServiceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serviceName_);
    }
    if (!getServiceVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serviceVersion_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tq.microservice.instanceregisterservice.RegisterInstanceRequest)) {
      return super.equals(obj);
    }
    com.tq.microservice.instanceregisterservice.RegisterInstanceRequest other = (com.tq.microservice.instanceregisterservice.RegisterInstanceRequest) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && (hasInstanceId() == other.hasInstanceId());
    if (hasInstanceId()) {
      result = result && getInstanceId()
          .equals(other.getInstanceId());
    }
    result = result && getServiceName()
        .equals(other.getServiceName());
    result = result && getServiceVersion()
        .equals(other.getServiceVersion());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasInstanceId()) {
      hash = (37 * hash) + INSTANCEID_FIELD_NUMBER;
      hash = (53 * hash) + getInstanceId().hashCode();
    }
    hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    hash = (37 * hash) + SERVICE_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getServiceVersion().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tq.microservice.instanceregisterservice.RegisterInstanceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code instanceregisterservice.RegisterInstanceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:instanceregisterservice.RegisterInstanceRequest)
      com.tq.microservice.instanceregisterservice.RegisterInstanceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tq.microservice.instanceregisterservice.InstanceRegisterServiceProto.internal_static_instanceregisterservice_RegisterInstanceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tq.microservice.instanceregisterservice.InstanceRegisterServiceProto.internal_static_instanceregisterservice_RegisterInstanceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tq.microservice.instanceregisterservice.RegisterInstanceRequest.class, com.tq.microservice.instanceregisterservice.RegisterInstanceRequest.Builder.class);
    }

    // Construct using com.tq.microservice.instanceregisterservice.RegisterInstanceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      if (instanceIdBuilder_ == null) {
        instanceId_ = null;
      } else {
        instanceId_ = null;
        instanceIdBuilder_ = null;
      }
      serviceName_ = "";

      serviceVersion_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tq.microservice.instanceregisterservice.InstanceRegisterServiceProto.internal_static_instanceregisterservice_RegisterInstanceRequest_descriptor;
    }

    @java.lang.Override
    public com.tq.microservice.instanceregisterservice.RegisterInstanceRequest getDefaultInstanceForType() {
      return com.tq.microservice.instanceregisterservice.RegisterInstanceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.tq.microservice.instanceregisterservice.RegisterInstanceRequest build() {
      com.tq.microservice.instanceregisterservice.RegisterInstanceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tq.microservice.instanceregisterservice.RegisterInstanceRequest buildPartial() {
      com.tq.microservice.instanceregisterservice.RegisterInstanceRequest result = new com.tq.microservice.instanceregisterservice.RegisterInstanceRequest(this);
      result.type_ = type_;
      if (instanceIdBuilder_ == null) {
        result.instanceId_ = instanceId_;
      } else {
        result.instanceId_ = instanceIdBuilder_.build();
      }
      result.serviceName_ = serviceName_;
      result.serviceVersion_ = serviceVersion_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tq.microservice.instanceregisterservice.RegisterInstanceRequest) {
        return mergeFrom((com.tq.microservice.instanceregisterservice.RegisterInstanceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tq.microservice.instanceregisterservice.RegisterInstanceRequest other) {
      if (other == com.tq.microservice.instanceregisterservice.RegisterInstanceRequest.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasInstanceId()) {
        mergeInstanceId(other.getInstanceId());
      }
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        onChanged();
      }
      if (!other.getServiceVersion().isEmpty()) {
        serviceVersion_ = other.serviceVersion_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tq.microservice.instanceregisterservice.RegisterInstanceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tq.microservice.instanceregisterservice.RegisterInstanceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.instanceregisterservice.InstanceType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.instanceregisterservice.InstanceType type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.instanceregisterservice.InstanceType type = 1;</code>
     */
    public com.tq.microservice.instanceregisterservice.InstanceType getType() {
      @SuppressWarnings("deprecation")
      com.tq.microservice.instanceregisterservice.InstanceType result = com.tq.microservice.instanceregisterservice.InstanceType.valueOf(type_);
      return result == null ? com.tq.microservice.instanceregisterservice.InstanceType.UNRECOGNIZED : result;
    }
    /**
     * <code>.instanceregisterservice.InstanceType type = 1;</code>
     */
    public Builder setType(com.tq.microservice.instanceregisterservice.InstanceType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.instanceregisterservice.InstanceType type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.tq.microservice.common.InstanceId instanceId_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tq.microservice.common.InstanceId, com.tq.microservice.common.InstanceId.Builder, com.tq.microservice.common.InstanceIdOrBuilder> instanceIdBuilder_;
    /**
     * <code>.common.InstanceId instanceId = 2;</code>
     */
    public boolean hasInstanceId() {
      return instanceIdBuilder_ != null || instanceId_ != null;
    }
    /**
     * <code>.common.InstanceId instanceId = 2;</code>
     */
    public com.tq.microservice.common.InstanceId getInstanceId() {
      if (instanceIdBuilder_ == null) {
        return instanceId_ == null ? com.tq.microservice.common.InstanceId.getDefaultInstance() : instanceId_;
      } else {
        return instanceIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.InstanceId instanceId = 2;</code>
     */
    public Builder setInstanceId(com.tq.microservice.common.InstanceId value) {
      if (instanceIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        instanceId_ = value;
        onChanged();
      } else {
        instanceIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.common.InstanceId instanceId = 2;</code>
     */
    public Builder setInstanceId(
        com.tq.microservice.common.InstanceId.Builder builderForValue) {
      if (instanceIdBuilder_ == null) {
        instanceId_ = builderForValue.build();
        onChanged();
      } else {
        instanceIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.common.InstanceId instanceId = 2;</code>
     */
    public Builder mergeInstanceId(com.tq.microservice.common.InstanceId value) {
      if (instanceIdBuilder_ == null) {
        if (instanceId_ != null) {
          instanceId_ =
            com.tq.microservice.common.InstanceId.newBuilder(instanceId_).mergeFrom(value).buildPartial();
        } else {
          instanceId_ = value;
        }
        onChanged();
      } else {
        instanceIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.common.InstanceId instanceId = 2;</code>
     */
    public Builder clearInstanceId() {
      if (instanceIdBuilder_ == null) {
        instanceId_ = null;
        onChanged();
      } else {
        instanceId_ = null;
        instanceIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.common.InstanceId instanceId = 2;</code>
     */
    public com.tq.microservice.common.InstanceId.Builder getInstanceIdBuilder() {
      
      onChanged();
      return getInstanceIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.InstanceId instanceId = 2;</code>
     */
    public com.tq.microservice.common.InstanceIdOrBuilder getInstanceIdOrBuilder() {
      if (instanceIdBuilder_ != null) {
        return instanceIdBuilder_.getMessageOrBuilder();
      } else {
        return instanceId_ == null ?
            com.tq.microservice.common.InstanceId.getDefaultInstance() : instanceId_;
      }
    }
    /**
     * <code>.common.InstanceId instanceId = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tq.microservice.common.InstanceId, com.tq.microservice.common.InstanceId.Builder, com.tq.microservice.common.InstanceIdOrBuilder> 
        getInstanceIdFieldBuilder() {
      if (instanceIdBuilder_ == null) {
        instanceIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tq.microservice.common.InstanceId, com.tq.microservice.common.InstanceId.Builder, com.tq.microservice.common.InstanceIdOrBuilder>(
                getInstanceId(),
                getParentForChildren(),
                isClean());
        instanceId_ = null;
      }
      return instanceIdBuilder_;
    }

    private java.lang.Object serviceName_ = "";
    /**
     * <code>string service_name = 3;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service_name = 3;</code>
     */
    public Builder setServiceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string service_name = 3;</code>
     */
    public Builder clearServiceName() {
      
      serviceName_ = getDefaultInstance().getServiceName();
      onChanged();
      return this;
    }
    /**
     * <code>string service_name = 3;</code>
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object serviceVersion_ = "";
    /**
     * <code>string service_version = 4;</code>
     */
    public java.lang.String getServiceVersion() {
      java.lang.Object ref = serviceVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service_version = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServiceVersionBytes() {
      java.lang.Object ref = serviceVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service_version = 4;</code>
     */
    public Builder setServiceVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string service_version = 4;</code>
     */
    public Builder clearServiceVersion() {
      
      serviceVersion_ = getDefaultInstance().getServiceVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string service_version = 4;</code>
     */
    public Builder setServiceVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceVersion_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:instanceregisterservice.RegisterInstanceRequest)
  }

  // @@protoc_insertion_point(class_scope:instanceregisterservice.RegisterInstanceRequest)
  private static final com.tq.microservice.instanceregisterservice.RegisterInstanceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tq.microservice.instanceregisterservice.RegisterInstanceRequest();
  }

  public static com.tq.microservice.instanceregisterservice.RegisterInstanceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterInstanceRequest>
      PARSER = new com.google.protobuf.AbstractParser<RegisterInstanceRequest>() {
    @java.lang.Override
    public RegisterInstanceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RegisterInstanceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegisterInstanceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterInstanceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tq.microservice.instanceregisterservice.RegisterInstanceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

