// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instanceregisterservice.proto

package com.tq.microservice.instanceregisterservice;

public interface UnregisterInstanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instanceregisterservice.UnregisterInstanceResponse)
    com.google.protobuf.MessageOrBuilder {
}
