// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instanceregisterservice.proto

package com.tq.microservice.instanceregisterservice;

public interface UnregisterInstanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instanceregisterservice.UnregisterInstanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.instanceregisterservice.InstanceType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.instanceregisterservice.InstanceType type = 1;</code>
   */
  com.tq.microservice.instanceregisterservice.InstanceType getType();

  /**
   * <code>.common.InstanceId instanceId = 2;</code>
   */
  boolean hasInstanceId();
  /**
   * <code>.common.InstanceId instanceId = 2;</code>
   */
  com.tq.microservice.common.InstanceId getInstanceId();
  /**
   * <code>.common.InstanceId instanceId = 2;</code>
   */
  com.tq.microservice.common.InstanceIdOrBuilder getInstanceIdOrBuilder();

  /**
   * <code>string service_name = 3;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string service_version = 4;</code>
   */
  java.lang.String getServiceVersion();
  /**
   * <code>string service_version = 4;</code>
   */
  com.google.protobuf.ByteString
      getServiceVersionBytes();
}
